version: '3.8'
services:
  web:
    image: 'scraper'
    container_name: 'scraper_api'
    restart: always
    build:
      context: .
      target: production
    ports:
      - 4200:4200
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    env_file:
      - .env
