version: "3.8"
services:
  web:
    container_name: "Web"
    build: 
      target: production
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    env_file:
      - .env