

#########
POST http://164.92.141.204:4200/api/search HTTP/1.1
Content-Type: application/json

{
    "Url" : "https://www.lcwaikiki.com/tr-TR/TR/urun/LC-WAIKIKI/kadin/Tunik/6195784/2569258"
}
######
POST http://164.92.141.204:4200/api/search HTTP/1.1
Content-Type: application/json

{
    "Url" : "https://www.lcwaikiki.com/tr-TR/TR/urun/LC-WAIKIKI/erkek-bebek/Takim/5954656/2494297",
    "Size": "9-12 Ay"
}
######
POST http://164.92.141.204:4200/api/search HTTP/1.1
Content-Type: application/json

{
    "Url" : "https://www.defacto.com.tr/regular-fit-bisiklet-yaka-kalin-kumas-bomber-ceket-2667336",
    "Size": "S"
}

######
POST http://164.92.141.204:4200/api/search HTTP/1.1
Content-Type: application/json

{
    "Url" : "https://www.koton.com/uzun-hirka-uzun-kollu-siyah-1266202/",
    "Size": "S"
}
######
POST http://164.92.141.204:4200/api/search HTTP/1.1
Content-Type: application/json

{
    "Url" : "https://www2.hm.com/tr_tr/productpage.1119492001.html",
    "Size": "M"
}
######
POST http://164.92.141.204:4200/api/search
Content-Type: application/json

{
    "Url" : "https://shop.mango.com/tr/kadin/ceketler-ve-blazer-ceketler/motorcu-tarz-fermuarl%C4%B1-ceket_37095951.html",
    "Size": "XS"
}



